### ISSUE TITLE
missing 1 required positional argument: 'zero_grad'

### ISSUE THREAD

**Issue by GavChap** [arogozhnikov/adamw_bfloat16#1]
In your README you state that the zero_grad argument is optional, however in your code it is not optional and I get this error when trying to use it the first way.

```python
# in the loop:
loss.backward()
optimizer.step()
optimizer.zero_grad()

**Comment by arogozhnikov** [comment]
check which version you use. Default one is this: https://github.com/arogozhnikov/adamw_bfloat16/blob/main/adamw_bfloat16/torchcompiled.py#L58
and zero_grad is optional there

**Comment by GavChap** [comment]
It's actually in _make_step() that the error happens.
```python
    lr: float,
    eps: float,
    decay_this_iteration: float,
    zero_grad: bool,
):
    exp_avg.mul_(beta1).add_(grad, alpha=1 - beta1)
    exp_avg_sq.mul_(beta2).addcmul_(grad, grad.conj(), value=1 - beta2)

**Comment by arogozhnikov** [comment]
thanks for pointing, should be fixed now on main
